name: Continuous integration

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
      - name: Run unit tests
        run: swift test
      - name: Validate configuration
        run: swift run endpoint-heartbeat validate --config Examples/heartbeat.json
