name: iOS compatibility

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  heartbeat:
    uses: ./.github/workflows/heartbeat-ios.yml
    with:
      config_path: Examples/heartbeat.json
      ios_version: "16.4"
      source_ref: ${{ github.sha }}
