name: On commit

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  continuous-integration:
    uses: ./.github/workflows/ci.yml
  heartbeat:
    uses: ./.github/workflows/heartbeat.yml
    with:
      source_ref: ${{ github.sha }}
