name: On commit

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  continuous-integration:
    uses: ./.github/workflows/ci.yml
  heartbeat:
    uses: ./.github/workflows/heartbeat.yml
    with:
      source_ref: ${{ github.sha }}
