name: On commit

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  continuous-integration:
    uses: ./.github/workflows/ci.yml
  heartbeat:
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/heartbeat.yml
    with:
      source_ref: ${{ github.sha }}
